{% set name = "ubergauss" %}
{% set version = "0.0.43" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ubergauss-{{ version }}.tar.gz
  sha256: 617701b2bc20f868596e38f9884522f18d34504c057aa0bb91b59702389f2551

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dill
    - lmz
    - numpy
    - python >={{ python_min }}
    - scikit-learn
    - scipy

test:
  imports:
    - ubergauss
    - ubergauss.optimization
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/smautner/ubergauss
  summary: sklearn clustering, betweenGaussian and diagonal-max-dist kneepoint detection
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smautner
